# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Good Intentions Assistant Framework
email: darren.m@firecreekweb.com
description: > # this means to ignore newlines until "baseurl:"
  Node.js Assistant framework designed for developers to quickly build chatbots and assistants
  with structure, conventions and useful utilities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goodintentionsassistant.github.io" # the base hostname & protocol for your site
github_username:  GoodIntentionsAssistant

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

kramdown:  
  parse_block_html: true
  auto_ids: true
